// <auto-generated />
using System;
using FilmLogAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmLogAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FilmLogAPI.Models.Movie", b =>
                {
                    b.Property<string>("MovieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Actors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("FilmLogAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FilmLogAPI.Models.WatchListMovie", b =>
                {
                    b.Property<int>("WatchlistId")
                        .HasColumnType("int");

                    b.Property<string>("MovieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.HasKey("WatchlistId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("WatchlistMovies");
                });

            modelBuilder.Entity("FilmLogAPI.Models.WatchedList", b =>
                {
                    b.Property<int>("WatchedlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WatchedlistId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WatchedlistId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("WatchedLists");
                });

            modelBuilder.Entity("FilmLogAPI.Models.WatchedListMovie", b =>
                {
                    b.Property<int>("WatchedListId")
                        .HasColumnType("int");

                    b.Property<string>("MovieId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TimesWatched")
                        .HasColumnType("int");

                    b.HasKey("WatchedListId", "MovieId");

                    b.HasIndex("MovieId");

                    b.ToTable("WatchedListMovies");
                });

            modelBuilder.Entity("FilmLogAPI.Models.Watchlist", b =>
                {
                    b.Property<int>("WatchlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WatchlistId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WatchlistId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Watchlists");
                });

            modelBuilder.Entity("FilmLogAPI.Models.WatchListMovie", b =>
                {
                    b.HasOne("FilmLogAPI.Models.Movie", "Movie")
                        .WithMany("WatchlistMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmLogAPI.Models.Watchlist", "Watchlist")
                        .WithMany("WatchlistMovies")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("FilmLogAPI.Models.WatchedList", b =>
                {
                    b.HasOne("FilmLogAPI.Models.User", "User")
                        .WithOne("WatchedList")
                        .HasForeignKey("FilmLogAPI.Models.WatchedList", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmLogAPI.Models.WatchedListMovie", b =>
                {
                    b.HasOne("FilmLogAPI.Models.Movie", "Movie")
                        .WithMany("WatchedListMovies")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FilmLogAPI.Models.WatchedList", "WatchedList")
                        .WithMany("WatchedListMovies")
                        .HasForeignKey("WatchedListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("WatchedList");
                });

            modelBuilder.Entity("FilmLogAPI.Models.Watchlist", b =>
                {
                    b.HasOne("FilmLogAPI.Models.User", "User")
                        .WithOne("Watchlist")
                        .HasForeignKey("FilmLogAPI.Models.Watchlist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FilmLogAPI.Models.Movie", b =>
                {
                    b.Navigation("WatchedListMovies");

                    b.Navigation("WatchlistMovies");
                });

            modelBuilder.Entity("FilmLogAPI.Models.User", b =>
                {
                    b.Navigation("WatchedList");

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("FilmLogAPI.Models.WatchedList", b =>
                {
                    b.Navigation("WatchedListMovies");
                });

            modelBuilder.Entity("FilmLogAPI.Models.Watchlist", b =>
                {
                    b.Navigation("WatchlistMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
